server:
  port: 8080
spring:
  thymeleaf:
    enabled: true
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: Spring Bootstrap
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;database_to_upper=false;DB_CLOSE_DELAY=-1
    #    url: jdbc:h2:file:./testdb;database_to_upper=false
    username: sa
    password: password
    sql-script-encoding: UTF-8
  h2:
    console:
      enabled: true
app:
  config:
    author: shinyay
